// Reads icons/*.svg and generates:
//   src/generated/icons.ts  - tree-shakeable IconNode exports (Check, ArrowRight, ...)
//   dist/svg/*.svg          - optimised raw SVG files
//   dist/sprite.svg         - <symbol> sprite (use with <svg><use href="sprite.svg#check"/></svg>)
//   dist/icons.json         - { name: IconNode } for tooling
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(root, 'icons');
const genDir = join(root, 'src/generated');
const distDir = join(root, 'dist');
mkdirSync(genDir, { recursive: true });
mkdirSync(join(distDir, 'svg'), { recursive: true });

const ELEMENT = /<(path|circle|rect|line|polyline|polygon|ellipse)\b([^>]*?)\/>/g;
const ATTR = /([a-zA-Z][\w-]*)="([^"]*)"/g;

export const pascal = (name) =>
  name.replace(/(^|-)([a-z0-9])/g, (_, __, ch) => ch.toUpperCase());

const files = readdirSync(srcDir).filter((f) => f.endsWith('.svg')).sort();
const icons = {};

for (const file of files) {
  const name = file.slice(0, -4);
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(name)) throw new Error(`Invalid icon name: ${name}`);
  const source = readFileSync(join(srcDir, file), 'utf8');
  const node = [];
  for (const [, tag, rawAttrs] of source.matchAll(ELEMENT)) {
    const attrs = {};
    for (const [, key, value] of rawAttrs.matchAll(ATTR)) attrs[key] = value;
    node.push([tag, attrs]);
  }
  if (!node.length) throw new Error(`Icon ${name} has no drawable elements`);
  icons[name] = node;
}

const toMarkup = (node) =>
  node
    .map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(' ')}/>`)
    .join('');

const SVG_OPEN =
  '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">';

let ts = `// Generated by scripts/build.mjs. Do not edit.\nimport { defineIcon } from '../define';\n\n`;
const symbols = [];
for (const [name, node] of Object.entries(icons)) {
  ts += `/** \`${name}\` icon */\nexport const ${pascal(name)} = /* @__PURE__ */ defineIcon('${name}', ${JSON.stringify(node)});\n`;
  writeFileSync(join(distDir, 'svg', `${name}.svg`), `${SVG_OPEN}${toMarkup(node)}</svg>\n`);
  symbols.push(`<symbol id="${name}" viewBox="0 0 24 24">${toMarkup(node)}</symbol>`);
}
ts += `\nexport const iconNames = ${JSON.stringify(Object.keys(icons))} as const;\nexport type IconName = (typeof iconNames)[number];\n`;

writeFileSync(join(genDir, 'icons.ts'), ts);
writeFileSync(
  join(distDir, 'sprite.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:none">\n${symbols.join('\n')}\n</svg>\n`,
);
writeFileSync(join(distDir, 'icons.json'), JSON.stringify(icons));
console.log(`Generated ${files.length} icons`);
